# Generated by Django 3.1.5 on 2021-01-20 01:31

from django.db import migrations, models
import django.db.models.deletion
import utils.model_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userservice', '0004_auto_20210115_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTransactions',
            fields=[
                ('id', models.CharField(default=utils.model_helpers.generate_id, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('deleted', 'deleted')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_status', models.CharField(choices=[('IN-PROGRESS', 'IN-PROGRESS'), ('CANCELLED', 'CANCELLED'), ('ABANDONED', 'ABANDONED'), ('COMPLETED', 'COMPLETED')], max_length=20)),
                ('closed_at', models.DateTimeField()),
                ('closed_by', models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('CUSTOMER', 'CUSTOMER'), ('AGENT', 'CUSTOMER')], max_length=20)),
                ('request_amount', models.IntegerField()),
                ('request_fees', models.IntegerField()),
                ('dest_latitude', models.FloatField(default=None, null=True)),
                ('dest_longitude', models.FloatField(default=None, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfiller', to='userservice.user', verbose_name='The user who is fufiling exchange request')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='userservice.user', verbose_name='The user who is requesting for exchange')),
            ],
            options={
                'db_table': 'ExchangeTransactions',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRequests',
            fields=[
                ('id', models.CharField(default=utils.model_helpers.generate_id, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('deleted', 'deleted')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=20)),
                ('request_id', models.CharField(max_length=70, verbose_name='The request id generated at agents search')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userservice.user', verbose_name='The user that would process this request')),
            ],
            options={
                'db_table': 'ExchangeRequests',
            },
        ),
        migrations.AddIndex(
            model_name='exchangetransactions',
            index=models.Index(fields=['state', 'transaction_status'], name='ExchangeTra_state_2a20fe_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerequests',
            index=models.Index(fields=['state', 'request_status', 'request_id'], name='ExchangeReq_state_5c45a1_idx'),
        ),
    ]
