# Generated by Django 3.1.5 on 2021-01-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactionservice', '0002_auto_20210121_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetransactions',
            name='request',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_request', to='transactionservice.exchangerequests', verbose_name='The request id for this exchange'),
        ),
        migrations.AlterField(
            model_name='exchangetransactions',
            name='closed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exchangetransactions',
            name='closed_by',
            field=models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('CUSTOMER', 'CUSTOMER'), ('AGENT', 'CUSTOMER')], default=None, max_length=20, null=True),
        ),
    ]
