# Generated by Django 3.1.5 on 2021-01-25 03:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionservice', '0003_auto_20210121_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequests',
            name='request_meta',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
