# Generated by Django 3.1.5 on 2021-01-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionservice', '0004_exchangerequests_request_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetransactions',
            name='cancellation_reason',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
    ]
