# Generated by Django 3.1.5 on 2021-02-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.model_helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactionservice', '0005_exchangetransactions_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionUserRatings',
            fields=[
                ('id', models.CharField(default=utils.model_helpers.generate_id, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('deleted', 'deleted')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_rating', models.PositiveIntegerField()),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL)),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactionservice.exchangetransactions')),
            ],
            options={
                'db_table': 'TransactionUserRatings',
            },
        ),
        migrations.AddIndex(
            model_name='transactionuserratings',
            index=models.Index(fields=['state'], name='Transaction_state_8ba551_idx'),
        ),
    ]
