# Generated by Django 3.1.5 on 2021-01-12 02:30

from django.db import migrations, models
import utils.model_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=utils.model_helpers.generate_id, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('deleted', 'deleted')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image_url', models.URLField(default='https://tudo-media.ams3.digitaloceanspaces.com/profile-images/USER_IMAGE_tko5rq.png')),
                ('transaction_pin', models.CharField(max_length=4, null=True)),
                ('bvn_number', models.CharField(max_length=11)),
                ('dob', models.DateField()),
                ('account_type', models.CharField(choices=[('Agent', 'Agent'), ('Customer', 'Customer')], max_length=20)),
                ('reg_mode', models.CharField(choices=[('Bank', 'Bank'), ('Bvn', 'Bvn')], max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state'], name='User_state_4e3365_idx'),
        ),
    ]
