# Generated by Django 3.1.5 on 2021-02-01 17:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0004_auto_20210115_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_meta',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
