# Generated by Django 3.1.5 on 2021-02-02 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.model_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0005_user_account_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='Unique device identifier', max_length=150, null=True, verbose_name='Device ID')),
                ('registration_id', models.TextField(verbose_name='Registration token')),
                ('type', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], max_length=10)),
                ('id', models.CharField(default=utils.model_helpers.generate_id, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('deleted', 'deleted')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserDevices',
            },
        ),
        migrations.AddIndex(
            model_name='userdevices',
            index=models.Index(fields=['state'], name='UserDevices_state_b4a91a_idx'),
        ),
    ]
