# Generated by Django 3.1.5 on 2021-04-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0008_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Customer', 'Customer')], default=None, max_length=20, null=True),
        ),
    ]
